services: 
  postgresDB:
    image: postgres:latest 
    volumes:
      - type: volume
        source: postgres_data 
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${SQLALCHEMY_DATABASE_USER}
      - POSTGRES_PASSWORD=${SQLALCHEMY_DATABASE_PASSWORD}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - postgresnet

  app:
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 3000:3000
    volumes:
      # Live reload (Development):
      - .:/app
    env_file:
      - .env
    networks:
      - postgresnet
    depends_on:
      - postgresDB

volumes:
  postgres_data:
    name: postgres_data

networks:
  postgresnet: 
